version: "3.1"

services:
  front:
    build: ./frontend
    depends_on:
      - api
    command: npm run serve
    container_name: giom_front
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./frontend/:/app/web
  api:
    build: ./backend
    depends_on:
      - db
    container_name: giom_api
    command: npm run start
    restart: always
    volumes:
      - ./backend/:/app/api
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: giomdb
      PORT: '3000'
      HOST: giom

  db:
    container_name: giomdb
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'giom_tecnologia'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./backend/script.sql:/docker-entrypoint-initdb.d/script.sql